name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: build
      shell: powershell
      run: |
        python -m pip install --upgrade wheel setuptools build pyinstaller
        python -m build
        pyinstaller --distpath=hd2macros --name "hd2_macros" --add-data ".\hd2_macros\config.toml:." -i .\hd2_macros.ico .\hd2_macros\__main__.py
        & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' inno.iss
        cd hd2macros
        7z a -r ..\hd2_macros.zip .
        cd ..

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: |
          dist/*
          innout/*
          hd2_macros.zip

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Release PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          innout/*
          hd2_macros.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
