name: release

on:
  push:
    tags:
      - 'v*.*.*'



jobs:
  build:
    permissions:
      id-token: write
      contents: read
    environment: deploy
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: build
      shell: powershell
      run: |
        python -m pip install --upgrade wheel setuptools build pyinstaller ahk ahk[binary] pydantic
        pip install -e .
        pyinstaller --distpath=hd2macros --name "hd2_macros" --add-data ".\hd2_macros\config.toml:." -i .\hd2_macros.ico --recursive-copy-metadata=hd2_macros .\hd2_macros\__main__.py

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: sign build
      uses: azure/trusted-signing-action@v0.3.18
      with:
        endpoint: ${{ secrets.SIGNING_ENDPOINT }}
        trusted-signing-account-name: ${{ secrets.CODE_SIGNING_ACCOUNT_NAME }}
        certificate-profile-name: ${{ secrets.CERTIFICATE_PROFILE_NAME }}
        files-folder: hd2macros\hd2_macros
        files-folder-filter: exe
        files-folder-recurse: false
        exclude-environment-credential: true
        exclude-workload-identity-credential: true
        exclude-managed-identity-credential: true
        exclude-shared-token-cache-credential: true
        exclude-visual-studio-credential: true
        exclude-visual-studio-code-credential: true
        exclude-azure-cli-credential: false
        exclude-azure-powershell-credential: true
        exclude-azure-developer-cli-credential: true
        exclude-interactive-browser-credential: true
        file-digest: SHA256
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256
    - name: package
      shell: powershell
      run: |
        python .\._getlicenses.py
        & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' inno.iss
        cd hd2macros
        7z a -r ..\hd2_macros.zip .
        cd ..

    - name: sign installer
      uses: azure/trusted-signing-action@v0.3.18
      with:
        endpoint: ${{ secrets.SIGNING_ENDPOINT }}
        trusted-signing-account-name: ${{ secrets.CODE_SIGNING_ACCOUNT_NAME }}
        certificate-profile-name: ${{ secrets.CERTIFICATE_PROFILE_NAME }}
        files-folder: innout
        files-folder-filter: exe
        files-folder-recurse: false
        exclude-environment-credential: true
        exclude-workload-identity-credential: true
        exclude-managed-identity-credential: true
        exclude-shared-token-cache-credential: true
        exclude-visual-studio-credential: true
        exclude-visual-studio-code-credential: true
        exclude-azure-cli-credential: false
        exclude-azure-powershell-credential: true
        exclude-azure-developer-cli-credential: true
        exclude-interactive-browser-credential: true
        file-digest: SHA256
        timestamp-rfc3161: http://timestamp.acs.microsoft.com
        timestamp-digest: SHA256

    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: |
          dist/*
          innout/*
          hd2_macros.zip

  release:
    environment: deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Release PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
    - name: Release GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          innout/*
          hd2_macros.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
